app:
  name: test
  description: test backend
  debug: true
  version: 1.0
  secret: "jwtsecret-kasdnisucrweis"
  tokenExpireTime: 2d
  refreshSecret: "fWSf!deVz@j+dH2Cvu6DNhAxs!gdq7+2"
  refreshTokenExpireTime: 14d
  otlExpireTime: 2M
  environment: "development"

mongo:
  test:
    url: mongodb://localhost:27017/test
  main:
    url: mongodb://localhost:27017/base


redis:
  host: "localhost"
  port: 6379
  name: main
  db: 0
  username:
  password:
  keyPrefix: